name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the 22.04 Docker image
      run: docker build m4abuild-base/22.04/Dockerfile --tag m4abuild-base:22.04
